[package]
name = "jsondocck-ng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
getopts = "0.2.21"
rustdoc-json-types = { path = "../../rustdoc-json-types" }
serde_json = "1.0.79"
